stages:
    - build
    - sentry
#    - deploy

build_job:
    image: docker:latest
    stage: build
    tags:
        - linux
        - dind
    script:
        - docker build --build-arg CI_BUILD_REF_NAME="$CI_BUILD_REF_NAME" -t exo-rp-altv .
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
        - docker tag exo-rp-altv $CI_REGISTRY_IMAGE:latest-$(echo $CI_BUILD_REF_NAME | tr -d /)
        - '[ "$CI_BUILD_REF_NAME" == "master" ] && docker tag exo-rp-altv $CI_REGISTRY_IMAGE:latest'
        - docker push "$CI_REGISTRY_IMAGE"
    only:
        - master
        - release/production

sentry_develop:
    image: getsentry/sentry-cli
    stage: sentry
    script:
        - VERSION=$(sentry-cli releases propose-version)
        - sentry-cli releases new -p "gtav-server" $VERSION
        - sentry-cli releases set-commits --auto $VERSION
        - sentry-cli releases deploys $VERSION new -e "develop"
    only:
        - master

#  deploy_job_develop:
#    image: ubuntu:latest
#    tags:
#      - linux
#      - dind
#    stage: deploy
#    script:
#      - apt-get update && apt-get install -y curl
#      - curl http://$DEPLOYRON_IP:6000/deploy/gta_develop?APISecret=$DEPLOY_API_SECRET_DEVELOP
#    only:
#      - master
  